// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1wYGW15FWHjhRk1L0GUYznXXSpVuDsek',
    appId: '1:1020935355775:web:2766a86f4b08faaf9aae4a',
    messagingSenderId: '1020935355775',
    projectId: 'education-system1',
    authDomain: 'education-system1.firebaseapp.com',
    storageBucket: 'education-system1.appspot.com',
    measurementId: 'G-SQDTC6BQ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNx0EmKLgs7f5rGnCWb43GshehoRa27a4',
    appId: '1:1020935355775:android:ae70c1526e8f152b9aae4a',
    messagingSenderId: '1020935355775',
    projectId: 'education-system1',
    storageBucket: 'education-system1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC842fq5evcqMt4Co1qPUYRjJCxLzNSwyA',
    appId: '1:1020935355775:ios:a687d7a3d5b57a5c9aae4a',
    messagingSenderId: '1020935355775',
    projectId: 'education-system1',
    storageBucket: 'education-system1.appspot.com',
    iosBundleId: 'com.example.educationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC842fq5evcqMt4Co1qPUYRjJCxLzNSwyA',
    appId: '1:1020935355775:ios:d00b2e0ef597b6939aae4a',
    messagingSenderId: '1020935355775',
    projectId: 'education-system1',
    storageBucket: 'education-system1.appspot.com',
    iosBundleId: 'com.example.educationSystem.RunnerTests',
  );
}
